apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: {{ .Values.frontend.port }}
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: {{ .Values.backend.port }}
  type: ClusterIP