name: Destroy Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to destroy"
        required: true
        default: "dev"
      confirm_destroy:
        description: "Type 'yes' to confirm destroy"
        required: true

jobs:
  destroy:
    if: ${{ github.event.inputs.confirm_destroy == 'yes' }}
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "ap-south-1"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -backend-config="region=ap-south-1" \
                            -backend-config="bucket=3tier-terraform-state" \
                            -backend-config="key=eks/terraform.tfstate" \
                            -backend-config="dynamodb_table=3tier-terraform-lock"

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -var="account_id=765455500374"
